# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f50a0939bfbf3db3d009b802781128812784c797b19465b1147773ba29cdd7a3bdc13a20be9123210e0239dca7661d25ef7ceae477acbf1fc4d3f15bd4e504e

test:
  secret_key_base: 83e901a9458851445b9df27ff4af6295a434c1535bcf112a95225b318a5be68f234ae68e03912005b46a273a18f25c2cab176ac5f52c30ab8a4c793b5ee86f53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
